version: '3'
services:
  # Backend NestJS
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongo

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

  # MongoDB
  mongo:
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
